doctrine:
    dbal:
        types:
            datetime_immutable: \Carbon\Doctrine\CarbonImmutableType
            datetime: \Carbon\Doctrine\CarbonType
            date: \Carbon\Doctrine\CarbonType

        override_url: true
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            my_entity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/my_entity/Entity'
                prefix: 'my_entity\Entity'
                alias: my_entity
            ProjectEntity:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/vendor/energy-solution/project-entity/src/Entity'
                prefix: 'ProjectEntity\Entity'
                alias: ProjectEntity
