controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation

my_entity:
    resource: ../../src/my_entity/Controller/
    type: annotation

